/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReflectRouteImport } from './routes/reflect'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as DiaryRouteImport } from './routes/diary'
import { Route as BrainstormRouteImport } from './routes/brainstorm'
import { Route as IndexRouteImport } from './routes/index'

const ReflectRoute = ReflectRouteImport.update({
  id: '/reflect',
  path: '/reflect',
  getParentRoute: () => rootRouteImport,
} as any)
const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const DiaryRoute = DiaryRouteImport.update({
  id: '/diary',
  path: '/diary',
  getParentRoute: () => rootRouteImport,
} as any)
const BrainstormRoute = BrainstormRouteImport.update({
  id: '/brainstorm',
  path: '/brainstorm',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/brainstorm': typeof BrainstormRoute
  '/diary': typeof DiaryRoute
  '/receive': typeof ReceiveRoute
  '/reflect': typeof ReflectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/brainstorm': typeof BrainstormRoute
  '/diary': typeof DiaryRoute
  '/receive': typeof ReceiveRoute
  '/reflect': typeof ReflectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/brainstorm': typeof BrainstormRoute
  '/diary': typeof DiaryRoute
  '/receive': typeof ReceiveRoute
  '/reflect': typeof ReflectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/brainstorm' | '/diary' | '/receive' | '/reflect'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/brainstorm' | '/diary' | '/receive' | '/reflect'
  id: '__root__' | '/' | '/brainstorm' | '/diary' | '/receive' | '/reflect'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BrainstormRoute: typeof BrainstormRoute
  DiaryRoute: typeof DiaryRoute
  ReceiveRoute: typeof ReceiveRoute
  ReflectRoute: typeof ReflectRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reflect': {
      id: '/reflect'
      path: '/reflect'
      fullPath: '/reflect'
      preLoaderRoute: typeof ReflectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diary': {
      id: '/diary'
      path: '/diary'
      fullPath: '/diary'
      preLoaderRoute: typeof DiaryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brainstorm': {
      id: '/brainstorm'
      path: '/brainstorm'
      fullPath: '/brainstorm'
      preLoaderRoute: typeof BrainstormRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BrainstormRoute: BrainstormRoute,
  DiaryRoute: DiaryRoute,
  ReceiveRoute: ReceiveRoute,
  ReflectRoute: ReflectRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
